/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenueVenueIdRouteImport } from './routes/venue.$venueId'
import { Route as VenueVenueIdBookRouteImport } from './routes/venue.$venueId_.book'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueVenueIdRoute = VenueVenueIdRouteImport.update({
  id: '/venue/$venueId',
  path: '/venue/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueVenueIdBookRoute = VenueVenueIdBookRouteImport.update({
  id: '/venue/$venueId_/book',
  path: '/venue/$venueId/book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/venue/$venueId': typeof VenueVenueIdRoute
  '/venue/$venueId/book': typeof VenueVenueIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/venue/$venueId': typeof VenueVenueIdRoute
  '/venue/$venueId/book': typeof VenueVenueIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/venue/$venueId': typeof VenueVenueIdRoute
  '/venue/$venueId_/book': typeof VenueVenueIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/venue/$venueId' | '/venue/$venueId/book'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/venue/$venueId' | '/venue/$venueId/book'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/venue/$venueId'
    | '/venue/$venueId_/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  VenueVenueIdRoute: typeof VenueVenueIdRoute
  VenueVenueIdBookRoute: typeof VenueVenueIdBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$venueId': {
      id: '/venue/$venueId'
      path: '/venue/$venueId'
      fullPath: '/venue/$venueId'
      preLoaderRoute: typeof VenueVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$venueId_/book': {
      id: '/venue/$venueId_/book'
      path: '/venue/$venueId/book'
      fullPath: '/venue/$venueId/book'
      preLoaderRoute: typeof VenueVenueIdBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  VenueVenueIdRoute: VenueVenueIdRoute,
  VenueVenueIdBookRoute: VenueVenueIdBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
